kind: pipeline
type: kubernetes
name: Build

steps:
- name: dotnet  
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet restore
  - dotnet build

trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
type: kubernetes
name: Release

steps:
- name: nuget  
  image: mcr.microsoft.com/dotnet/sdk:6.0
  environment:
    TOKEN:
      from_secret: TOKEN_NUGET
  commands:
  - dotnet pack --configuration Release -p:PackageVersion=$DRONE_TAG -p:Version=$DRONE_TAG -p:AssemblyVersion=$DRONE_TAG -p:SymbolPackageFormat=snupkg gitRelease.csproj
  - dotnet nuget push ./nupkg/gitRelease.*.nupkg -s https://www.nuget.org/api/v2/package -k $TOKEN --skip-duplicate --timeout 1000
- name: Docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/gitrelease
    auto_tag: true
- name: Docker2  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: Dockerfile2
    repo: craftingit/gitrelease
    tags:
      - base
- name: build files  
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet publish -o outWin -r win-x64 -c Release --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -p:Version=$DRONE_TAG -p:AssemblyVersion=$DRONE_TAG /p:DebugType=None /p:IncludeSymbolsInSingleFile=false gitRelease.csproj
  - dotnet publish -o outLin -r linux-x64 -c Release --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -p:Version=$DRONE_TAG -p:AssemblyVersion=$DRONE_TAG /p:DebugType=None /p:IncludeSymbolsInSingleFile=false gitRelease.csproj
  - dotnet publish -o outOsx -r osx-x64 -c Release --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -p:Version=$DRONE_TAG -p:AssemblyVersion=$DRONE_TAG /p:DebugType=None  /p:IncludeSymbolsInSingleFile=false gitRelease.csproj
- name: zip files
  image: craftingit/ci-tools-docker
  commands:
    - zip -r win-x64_gitRelease.zip outWin
    - zip -r linux-x64_gitRelease.zip outLin
    - zip -r osx-x64_gitRelease.zip outLin
- name: upload files
  image: craftingit/gitrelease  
  environment:
    TOKEN:
      from_secret: TOKEN_GITHUB
  commands:
    - gitRelease github upload --tag $DRONE_TAG --ApiToken ${token} --owner CraftingITde --repo gitRelease --filename win-x64_gitRelease.zip
    - gitRelease github upload --tag $DRONE_TAG --ApiToken ${token} --owner CraftingITde --repo gitRelease --filename linux-x64_gitRelease.zip
    - gitRelease github upload --tag $DRONE_TAG --ApiToken ${token} --owner CraftingITde --repo gitRelease --filename osx-x64_gitRelease.zip

trigger:
  event:
  - tag
