<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="deps\**" />
    <Compile Remove="Gitea.API\**" />
    <EmbeddedResource Remove="deps\**" />
    <EmbeddedResource Remove="Gitea.API\**" />
    <None Remove="deps\**" />
    <None Remove="Gitea.API\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Octokit" Version="0.40.0" />
    <PackageReference Include="CommandLineParser" Version="2.7.82" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="CommandLineParser.2.6.0\.signature.p7s" />
    <None Remove="CommandLineParser.2.6.0\README.md" />
    <None Remove="CommandLineParser.2.6.0\lib\netstandard2.0\CommandLine.xml" />
    <None Remove="CommandLineParser.2.6.0\lib\netstandard2.0\CommandLine.dll" />
    <None Remove="CommandLineParser.2.6.0\lib\net45\CommandLine.xml" />
    <None Remove="CommandLineParser.2.6.0\lib\net45\CommandLine.dll" />
    <None Remove="CommandLineParser.2.6.0\lib\net40\CommandLine.xml" />
    <None Remove="CommandLineParser.2.6.0\lib\net40\CommandLine.dll" />
    <None Remove="CommandLineParser.2.6.0\CommandLineParser.2.6.0.nupkg" />
    <None Remove="CommandLineParser.2.6.0\lib\net461\CommandLine.xml" />
    <None Remove="CommandLineParser.2.6.0\lib\net461\CommandLine.dll" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="Gitea.API\Gitea.API.csproj" />
  </ItemGroup>
</Project>
